name: stacked_notification_cards
description: A Flutter implementation of iOS style stacked notifications which can be dismissed.
repository: https://github.com/OakTree-Apps/stacked_notification_cards

version: 0.1.0-dev.6

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
